/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Thu Jun 16 18:00:23 2016. */

#include "PositionSensor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t PositionSensorTelemetry_fields[3] = {
    PB_FIELD(  1, SFIXED32, REQUIRED, STATIC  , FIRST, PositionSensorTelemetry, x, x, 0),
    PB_FIELD(  2, SFIXED32, REQUIRED, STATIC  , OTHER, PositionSensorTelemetry, y, x, 0),
    PB_LAST_FIELD
};

const pb_field_t PositionSensorCommand_fields[2] = {
    PB_FIELD(  1, SFIXED32, REQUIRED, STATIC  , FIRST, PositionSensorCommand, command, command, 0),
    PB_LAST_FIELD
};

const pb_field_t PositionSensorStatus_fields[2] = {
    PB_FIELD(  1, SFIXED32, REQUIRED, STATIC  , FIRST, PositionSensorStatus, status, status, 0),
    PB_LAST_FIELD
};

const pb_field_t PositionSensor_fields[5] = {
    PB_FIELD(  1, SFIXED32, REQUIRED, STATIC  , FIRST, PositionSensor, pid, pid, 0),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , OTHER, PositionSensor, status, pid, &PositionSensorStatus_fields),
    PB_ONEOF_FIELD(payload,   3, MESSAGE , ONEOF, STATIC  , OTHER, PositionSensor, command, pid, &PositionSensorCommand_fields),
    PB_ONEOF_FIELD(payload,   4, MESSAGE , ONEOF, STATIC  , OTHER, PositionSensor, telemetry, pid, &PositionSensorTelemetry_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PositionSensor, payload.status) < 65536 && pb_membersize(PositionSensor, payload.command) < 65536 && pb_membersize(PositionSensor, payload.telemetry) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_PositionSensorTelemetry_PositionSensorCommand_PositionSensorStatus_PositionSensor)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(PositionSensor, payload.status) < 256 && pb_membersize(PositionSensor, payload.command) < 256 && pb_membersize(PositionSensor, payload.telemetry) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_PositionSensorTelemetry_PositionSensorCommand_PositionSensorStatus_PositionSensor)
#endif


/* @@protoc_insertion_point(eof) */
